#!/usr/bin/env python3
# -*- mode: python; coding: utf-8 -*-
"""
Interact with Logitech Media Server

Usage:
  lms (-h | --help)
  lms --version
  lms [-v|-vv] [options] status
  lms [-v|-vv] [options] <player> (play | pause)
  lms [-v|-vv] [options] <player> (play | add) <track>
  lms [-v|-vv] [options] <player> volume (up | down | <vol>)

Options:
  -h --help             Show this message
  -v,-vv                Increase verbosity
  --version             Show version
"""

import docopt
import logging
from time import time
from json import dumps as to_json
from sys import stderr
from collections import OrderedDict
from lms import find_server, __version__
from re import match

_LOGGER = logging.getLogger(__name__)

LOGFMT = "%(asctime)s %(levelname)5s (%(threadName)s) [%(name)s] %(message)s"
DATEFMT = "%y-%m-%d %H:%M.%S"


def timeFmt(secs):
    if not secs:
        return ''
    h, r = divmod(secs, 3600)
    m, secs = divmod(r, 60)
    return '%s%02d.%02d' % ('' if not h else '%02d:' % h, m, secs)


def main():
    """Command line interface."""
    args = docopt.docopt(__doc__,
                         version=__version__)

    log_level = [logging.ERROR, logging.INFO, logging.DEBUG][args['-v']]

    try:
        import coloredlogs
        coloredlogs.install(level=log_level,
                            stream=stderr,
                            datefmt=DATEFMT,
                            fmt=LOGFMT)
    except ImportError:
        _LOGGER.debug("no colored logs. pip install coloredlogs?")
        logging.basicConfig(level=log_level,
                            stream=stderr,
                            datefmt=DATEFMT,
                            format=LOGFMT)

    server = find_server()

    player_id = args['<player>']
    player = (next((
        player for player in server.players
        if player_id.lower() in [
                player.player_id,
                player.name.lower(),
                player.ip]), None)
              if player_id else None)

    if args['<track>']:
        if 'spotify' in args['<track>'] and not server.can('spotty'):
            exit('Spotty not supported by server')
        m = match('https://open.spotify.com/(track|album|playlist)/([0-9a-zA-Z]*)', args['<track>'])
        if m:
            args['<track>'] = 'spotify:%s:%s' % m.groups()

    if args['status']:
        print(f'{server._host}:{server._port} ({server.version})')
        for player in server.players:
            if player.is_playing:
                status = 'playing'
            elif player.is_paused:
                status = 'paused'
            elif player.is_stopped:
                status = 'stopped'
            else:
                status = '?'
            print(f'- {player.name:10} {player.model:16} '
                  f'{player.ip:15} 📶{player.wifi_signal_strength:>4}% '
                  f'{status:7} '
                  f'{(player.artist or "")[:10]:10} {(player.title or "")[:10]:10} '
                  f'{round(player.position_pct):3}% '
                  f'{timeFmt(player.position) or "     "}/'
                  f'{timeFmt(player.duration) or "     "} ')

    #    url='https://open.spotify.com/track/4uLU6hMCjMI75M1A2tKUQC'
    #    server.players[0].query('playlist', 'play', url)
    elif player:
        if args['<track>']:
            if args['play']:
                player.play_uri(args['<track>'])
            elif args['add']:
                player.add_uri(args['<track>'])
        elif args['play']:
            player.play()
        elif args['pause']:
            player.pause()
        elif args['volume']:
            if args['<vol>']:
                player.set_volume(args['<vol>'])
            elif args['up']:
                player.volume_up()
            elif args['down']:
                player.volume_down()
    else:
        exit('?')


if __name__ == '__main__':
   main()
