#!/usr/bin/env python3
# -*- mode: python; coding: utf-8 -*-
"""
Interact with Logitech Media Server

Usage:
  lms (-h | --help)
  lms --version
  lms [-v|-vv] [options] status
  lms [-v|-vv] [options] <player> (play | pause)
  lms [-v|-vv] [options] <player> (play | add) <track>
  lms [-v|-vv] [options] <player> volume (up | down | <vol>)

Options:
  -h --help             Show this message
  -v,-vv                Increase verbosity
  --version             Show version
"""

import docopt
import logging
from time import time
from json import dumps as to_json
from sys import stderr
from collections import OrderedDict
from lms import find_server, __version__

_LOGGER = logging.getLogger(__name__)

LOGFMT = "%(asctime)s %(levelname)5s (%(threadName)s) [%(name)s] %(message)s"
DATEFMT = "%y-%m-%d %H:%M.%S"


def timeFmt(secs):
    h, r = divmod(secs, 3600)
    m, secs = divmod(r, 60)
    return '%s%02d.%02d' % ('' if not h else '%02d:' % h, m, secs)


def main():
    """Command line interface."""
    args = docopt.docopt(__doc__,
                         version=__version__)

    log_level = [logging.ERROR, logging.INFO, logging.DEBUG][args['-v']]

    try:
        import coloredlogs
        coloredlogs.install(level=log_level,
                            stream=stderr,
                            datefmt=DATEFMT,
                            fmt=LOGFMT)
    except ImportError:
        _LOGGER.debug("no colored logs. pip install coloredlogs?")
        logging.basicConfig(level=log_level,
                            stream=stderr,
                            datefmt=DATEFMT,
                            format=LOGFMT)

    server = find_server()

    player_id = args['<player>']
    player = (next((
        player for player in server.players
        if player_id.lower() in [
                player.player_id,
                player.name.lower(),
                player.ip]), None)
              if player_id else None)

    if args['status']:
        print(f'{server._host}:{server._port} ({server.version})')
        for player in server.players:
            print(f'- {player.name:10} {player.model:16} '
                  f'{player.ip:15} 📶{player.wifi_signal_strength:>4}% '
                  f'{"playing" if player.is_playing else "paused" if player.is_paused else "stopped" if player.is_stopped else "?":7} '
                  f'{(player.artist or "")[:10]:10} {player.title[:10]:10} '
                  f'{timeFmt(player.position)}/'
                  f'{timeFmt(player.duration) or "?"} '
                  f'({round(player.position_pct):3}%)')

    elif player:
        if args['<track>']:
            if args['play']:
                pass
            elif args['add']:
                pass
        elif args['play']:
            player.play()
        elif args['pause']:
            player.pause()
        elif args['volume']:
            if args['<vol>']:
                player.set_volume(args['<vol>'])
            elif args['up']:
                player.volume_up()
            elif args['down']:
                player.volume_down()
    else:
        exit('?')


if __name__ == '__main__':
   main()
